// Code generated by mockery v2.27.1. DO NOT EDIT.

package inventoryMocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	inventorypb "order-service/proto/inventorypb"

	mock "github.com/stretchr/testify/mock"
)

// InventoryServiceClient is an autogenerated mock type for the InventoryServiceClient type
type InventoryServiceClient struct {
	mock.Mock
}

// GetItem provides a mock function with given fields: ctx, in, opts
func (_m *InventoryServiceClient) GetItem(ctx context.Context, in *inventorypb.GetItemRequest, opts ...grpc.CallOption) (*inventorypb.GetItemResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *inventorypb.GetItemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventorypb.GetItemRequest, ...grpc.CallOption) (*inventorypb.GetItemResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *inventorypb.GetItemRequest, ...grpc.CallOption) *inventorypb.GetItemResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventorypb.GetItemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *inventorypb.GetItemRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LowerQuantity provides a mock function with given fields: ctx, in, opts
func (_m *InventoryServiceClient) LowerQuantity(ctx context.Context, in *inventorypb.LowerQuantityRequest, opts ...grpc.CallOption) (*inventorypb.LowerQuantityResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *inventorypb.LowerQuantityResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *inventorypb.LowerQuantityRequest, ...grpc.CallOption) (*inventorypb.LowerQuantityResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *inventorypb.LowerQuantityRequest, ...grpc.CallOption) *inventorypb.LowerQuantityResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*inventorypb.LowerQuantityResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *inventorypb.LowerQuantityRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewInventoryServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewInventoryServiceClient creates a new instance of InventoryServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInventoryServiceClient(t mockConstructorTestingTNewInventoryServiceClient) *InventoryServiceClient {
	mock := &InventoryServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
