// Code generated by mockery v2.27.1. DO NOT EDIT.

package ordermocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	order "api-gateway/proto/order"
)

// OrderServiceClient is an autogenerated mock type for the OrderServiceClient type
type OrderServiceClient struct {
	mock.Mock
}

// GetAllOrders provides a mock function with given fields: ctx, in, opts
func (_m *OrderServiceClient) GetAllOrders(ctx context.Context, in *order.GetAllOrdersRequest, opts ...grpc.CallOption) (*order.GetAllOrdersResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order.GetAllOrdersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order.GetAllOrdersRequest, ...grpc.CallOption) (*order.GetAllOrdersResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order.GetAllOrdersRequest, ...grpc.CallOption) *order.GetAllOrdersResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.GetAllOrdersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order.GetAllOrdersRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrder provides a mock function with given fields: ctx, in, opts
func (_m *OrderServiceClient) GetOrder(ctx context.Context, in *order.GetOrderRequest, opts ...grpc.CallOption) (*order.GetOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order.GetOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order.GetOrderRequest, ...grpc.CallOption) (*order.GetOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order.GetOrderRequest, ...grpc.CallOption) *order.GetOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.GetOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order.GetOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaceOrder provides a mock function with given fields: ctx, in, opts
func (_m *OrderServiceClient) PlaceOrder(ctx context.Context, in *order.PlaceOrderRequest, opts ...grpc.CallOption) (*order.PlaceOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *order.PlaceOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order.PlaceOrderRequest, ...grpc.CallOption) (*order.PlaceOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order.PlaceOrderRequest, ...grpc.CallOption) *order.PlaceOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.PlaceOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order.PlaceOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewOrderServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewOrderServiceClient creates a new instance of OrderServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOrderServiceClient(t mockConstructorTestingTNewOrderServiceClient) *OrderServiceClient {
	mock := &OrderServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
